;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-paren
	c-electric-semi&comma
	c-indent-line-or-region
	indent-for-tab-command
	kill-region
	mouse-save-then-kill
	upcase-region
	))

(setq mc/cmds-to-run-once
      '(
	ace-jump-mode
	c-electric-pound
	c-electric-slash
	c-show-syntactic-information
	c-toggle-auto-newline
	c-up-conditional
	comment-region
	describe-key
	goto-line
	neotree-create-node
	sql-send-paragraph
	))
